# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [86]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error as mae
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [87]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [88]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [89]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [90]:
X = data.drop(columns='MEDV')
y = data['MEDV']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape


((404, 13), (102, 13), (404,), (102,))

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [91]:
lr_model = LinearRegression()

lr_model.fit(X_train, y_train)

pred_train = lr_model.predict(X_train)
pred_test = lr_model.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [92]:
r2_train = r2_score(y_train, pred_train)
r2_test = r2_score(y_test, pred_test)

print(f'The r2 Score for the training set is: {r2_train:.4f}')
print(f'The r2 Score for the test set is: {r2_test:.4f}')

The r2 Score for the training set is: 0.7509
The r2 Score for the test set is: 0.6688


## 4. Calculate and print mean squared error for both the training and the testing set.

In [93]:
mse_train = mean_squared_error(y_train, pred_train)
mse_test = mean_squared_error(y_test, pred_test)

rmse_train = np.sqrt(mse_train)
rmse_test = np.sqrt(mse_test)

print(f'The Mean Squared Error for the training set is: {mse_train:.4f}')
print(f'The Mean Squared Error for the test set is: {mse_test:.4f}')

print(f'The Root Mean Square Error for the train set is: ${(rmse_train)*1000:.2f}')
print(f'The Root Mean Square Error for the test set is: ${(rmse_test)*1000:.2f}')

The Mean Squared Error for the training set is: 21.6414
The Mean Squared Error for the test set is: 24.2911
The Root Mean Square Error for the train set is: $4652.03
The Root Mean Square Error for the test set is: $4928.60


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [94]:
mae_train = mae(y_train, pred_train)
mae_test = mae(y_test, pred_test)

print(f'The Mean Absolute Error for the training set is: {mae_train:.4f}')
print(f'The Mean Absolute Error for the testing set is: {mae_test:.4f}')

The Mean Absolute Error for the training set is: 3.3148
The Mean Absolute Error for the testing set is: 3.1891


## Classification Model Evaluation

In [109]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score, 
    precision_score, 
    recall_score, 
    f1_score, 
    confusion_matrix
)
data = load_iris()

In [96]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [97]:
column_names = data.feature_names

In [98]:
df = pd.DataFrame(data['data'],columns=column_names)

In [99]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [100]:
target = pd.DataFrame(data.target)

In [101]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [102]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [ ]:
df['class'] = target

X = df.drop(columns='class')
y = df['class']

# Sanity checks on shapes to see if they match before splitting
#print(X.shape, y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Sanity check on shapes after split and confirming the stratify argument kept the splits proportional
#print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(150, 4) (150,)
(120, 4) (30, 4) (120,) (30,)


## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [111]:
log_reg_model = LogisticRegression()

log_reg_model.fit(X_train, y_train)

log_pred_train = log_reg_model.predict(X_train)
log_pred_test = log_reg_model.predict(X_test)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [113]:
train_acc_score = accuracy_score(y_train, log_pred_train)
test_acc_score = accuracy_score(y_test, log_pred_test)

print(f'The accuracy score for the training set was: {train_acc_score:.4f}')
print(f'The accuracy score for the testing set was: {test_acc_score:.4f}')

The accuracy score for the training set was: 0.9750
The accuracy score for the testing set was: 0.9667


### Opinion:
The results show a very high accuracy due to the well balanced dataset we have for each class. Almost similar results allude to a very good generalization

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [114]:
train_bal_acc_score = balanced_accuracy_score(y_train, log_pred_train)
test_bal_acc_score = balanced_accuracy_score(y_test, log_pred_test)

print(f'The balanced accuracy score for the training set was: {train_bal_acc_score:.4f}')
print(f'The balanced accuracy score for the testing set was: {test_bal_acc_score:.4f}')

The balanced accuracy score for the training set was: 0.9750
The balanced accuracy score for the testing set was: 0.9667


## 10. Calculate and print the precision score for both the training and the testing set.

In [117]:
train_precision_score = precision_score(y_train, log_pred_train, average='weighted')
test_precision_score = precision_score(y_test, log_pred_test, average='weighted')

print(f'The precision score for the training set was: {train_precision_score:.4f}')
print(f'The precision score for the testing set was: {test_precision_score:.4f}')

The precision score for the training set was: 0.9752
The precision score for the testing set was: 0.9697


## 11. Calculate and print the recall score for both the training and the testing set.

In [118]:
train_recall_score = recall_score(y_train, log_pred_train, average='weighted')
test_recall_score = recall_score(y_test, log_pred_test, average='weighted')

print(f'The recall score for the training set was: {train_recall_score:.4f}')
print(f'The recall score for the testing set was: {test_recall_score:.4f}')

The recall score for the training set was: 0.9750
The recall score for the testing set was: 0.9667


## 12. Calculate and print the F1 score for both the training and the testing set.

In [119]:
train_f1_score = f1_score(y_train, log_pred_train, average='weighted')
test_f1_score = f1_score(y_test, log_pred_test, average='weighted')

print(f'The F1 score for the training set was: {train_f1_score:.4f}')
print(f'The F1 score for the testing set was: {test_f1_score:.4f}')

The F1 score for the training set was: 0.9750
The F1 score for the testing set was: 0.9666


## 13. Generate confusion matrices for both the training and the testing set.

In [121]:
train_confusion_matrix = confusion_matrix(y_train, log_pred_train)
test_confusion_matrix = confusion_matrix(y_test, log_pred_test)

print(train_confusion_matrix)
print('\n')
print(test_confusion_matrix)

[[40  0  0]
 [ 0 38  2]
 [ 0  1 39]]


[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


### Interpretation
The evaluation results tells the Iris Dataset is very well balanced between the classes and this allows the Classification models to behave very well here in terms of training and testing on unseen data. The Logistic Regression model makes very few errors and no class is being ignored or over weighted. This means the classes are nearly linearly separable.
The stratify parameter helps to ensure all classes are proportionally demonstrated in our splits avoiding class misrepresentation on smaller datasets as this one.

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [ ]:
# Have fun here !